### ISSUE TITLE
A companion application

### ISSUE THREAD

**Issue by nicholasMichaelHall07** [marklieberman/youtube-dl-button#4]
Where can i get it?

**Comment by marklieberman** [comment]
I made one for windows here https://github.com/marklieberman/youtube-dl-button-native-apps but the install script is not ready. If you want to use it you'll have to create the [native manfiest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests) and registry entries yourself.

**Comment by nicholasMichaelHall07** [comment]
Ok. Whenever you've got time.
